plugins { id 'java-library' }
repositories { mavenCentral() }
java { sourceCompatibility=JavaVersion.VERSION_25;targetCompatibility=JavaVersion.VERSION_25 }
dependencies {
 api 'gg.kembel.dui:dui-core:0.2.0-SNAPSHOT'
 compileOnly 'gg.kembel.dui:dui-pack:0.2.0-SNAPSHOT'
 testImplementation 'gg.kembel.dui:dui-pack:0.2.0-SNAPSHOT'
 testImplementation platform('org.junit:junit-bom:5.14.0')
 testImplementation 'org.junit.jupiter:junit-jupiter'
 testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
test {useJUnitPlatform()}
